
version: '3.8' 
services: 
app: 
build: . 
ports: - "5000:5000" 
environment: - FLASK_ENV=development 
depends_on: - db 
db: 
image: mysql:8 
environment: 
MYSQL_ROOT_PASSWORD: example 
MYSQL_DATABASE: prod_db 
ports: - "3306:3306"
